### ISSUE TITLE
API format needs to standardized

### ISSUE THREAD

**Issue by NickAnastasoff** [NickAnastasoff/THE_LOBSTER#9]
api has csv values in random order

**Comment by NickAnastasoff** [comment]
Temperature
pH
Salinity
Accelerometer
Flood Detection
Wattage
time
all sensors what order?

**Comment by NickAnastasoff** [comment]
Date, temp, ph, ec, flood Detection, wattage, Accelerometer is the format

**Comment by freyjaprescott** [comment]
Date, temp, ph, ec, flood Detection, wattage, air temp, air humidity, Accelerometer is the format

**Comment by NickAnastasoff** [comment]
api has great format
